name: AI Docs Critic
on:
  pull_request:
    types:
      - opened
      - synchronize
permissions: write-all
jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: AI Docs Critic
        uses: johndmulhausen/ai-docs-critic@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_API_MODEL: "gpt-4" # Optional: defaults to "gpt-4"
          exclude: "**/*.json, **/*.html, **/*.txt, **/*.yml, **.*.yaml, **/*.toml, **/*.js, **/*.sass, **/*.css" # Optional: exclude patterns separated by commas
